all:
	g++ Neuron.cpp NeuronTest.cpp \
	../ActivationFunctions/ActivationFunctionIO.cpp ../ActivationFunctions/ReluActivationFunction.cpp ../ActivationFunctions/LeakyReluActivationFunction.cpp ../ActivationFunctions/LinearActivationFunction.cpp ../ActivationFunctions/SigmoidActivationFunction.cpp ../ActivationFunctions/TanhActivationFunction.cpp \
	../NeuronWeightInitializers/NeuronWeightInitializerIO.cpp ../NeuronWeightInitializers/UniformlyRandomNeuronWeightInitializer.cpp \
	-o NeuronTest