all:
	g++ Layer.cpp LayerTest.cpp ../ActivationFunctions/ReluActivationFunction.cpp ../Neurons/Neuron.cpp -o LayerTest

	g++ NeuralNetwork.cpp NeuralNetworkTest.cpp ../Layers/Layer.cpp ../Neurons/Neuron.cpp ../ActivationFunctions/ReluActivationFunction.cpp ../ActivationFunctions/TanhActivationFunction.cpp ../LossFunctions/SquaredErrorLossFunction.cpp -o NeuralNetworkTest