all:
	g++ Layer.cpp LayerTest.cpp \
	../ActivationFunctions/ActivationFunctionIO.cpp ../ActivationFunctions/ReluActivationFunction.cpp ../ActivationFunctions/LeakyReluActivationFunction.cpp ../ActivationFunctions/LinearActivationFunction.cpp ../ActivationFunctions/SigmoidActivationFunction.cpp ../ActivationFunctions/TanhActivationFunction.cpp \
	../NeuronWeightInitializers/NeuronWeightInitializerIO.cpp ../NeuronWeightInitializers/UniformlyRandomNeuronWeightInitializer.cpp \
	../Neurons/Neuron.cpp \
	-o LayerTest