all:
	g++ Classifier.cpp \
	../NeuralNetwork/NeuralNetwork.cpp \
	../Layers/Layer.cpp \
	../Neurons/Neuron.cpp \
	../Datasets/Dataset.cpp \
	../ActivationFunctions/ActivationFunctionIO.cpp ../ActivationFunctions/ReluActivationFunction.cpp ../ActivationFunctions/TanhActivationFunction.cpp ../ActivationFunctions/LeakyReluActivationFunction.cpp ../ActivationFunctions/LinearActivationFunction.cpp ../ActivationFunctions/SigmoidActivationFunction.cpp \
	../LossFunctions/LossFunctionIO.cpp ../LossFunctions/SquaredErrorLossFunction.cpp ../LossFunctions/LogCoshLossFunction.cpp \
	../NeuronWeightInitializers/NeuronWeightInitializerIO.cpp ../NeuronWeightInitializers/UniformlyRandomNeuronWeightInitializer.cpp \
	-o Classifier